version: 2.1

jobs:
  venv-and-test:
#    machine:
#      resource_class: gpu.nvidia.small
#      image: ubuntu-1604-cuda-10.1:201909-23
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Create virtual environment and install test dependencies
          command: |
            python3 -m venv env_fidelity
            . env_fidelity/bin/activate
            pip3 install --upgrade pip
            pip3 install -r tests/requirements_test.txt
            echo "export PYTHONPATH=.:$PYTHONPATH" >> $BASH_ENV
      - run:
          name: Test interpolation on cpu
          command: |
            . env_fidelity/bin/activate
            CUDA_VISIBLE_DEVICES="" python3 ./tests/precision/test_interpolation.py
#      - run:
#          name: Test interpolation on gpu
#          command: |
#            . env_fidelity/bin/activate
#            CUDA_VISIBLE_DEVICES=0 python3 ./tests/precision/test_interpolation.py
      - run:
          name: Test convolution on cpu
          command: |
            . env_fidelity/bin/activate
            CUDA_VISIBLE_DEVICES="" python3 ./tests/precision/test_convolution.py
#      - run:
#          name: Test convolution on gpu
#          command: |
#            . env_fidelity/bin/activate
#            CUDA_VISIBLE_DEVICES=0 python3 ./tests/precision/test_convolution.py
      - run:
          name: Test inception on cpu
          command: |
            . env_fidelity/bin/activate
            CUDA_VISIBLE_DEVICES="" python3 ./tests/precision/test_inception.py
#      - run:
#          name: Test inception on gpu
#          command: |
#            . env_fidelity/bin/activate
#            CUDA_VISIBLE_DEVICES=0 python3 ./tests/precision/test_inception.py
      - run:
          name: Organize artifacts
          command: |
            mkdir -p artifacts
            mv *.png artifacts/
      - store_artifacts:
          path: artifacts
          destination: test_images

workflows:
  main:
    jobs:
      - venv-and-test
