version: 2.1

jobs:
  venv-and-test:
#    machine:
#      resource_class: gpu.nvidia.small
#      image: ubuntu-1604-cuda-10.1:201909-23
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv env_fidelity
            . env_fidelity/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements_test.txt
      - run:
          name: test_interpolation_cpu
          command: |
            . env_fidelity/bin/activate
            export CUDA_VISIBLE_DEVICES=""
            python3 ./test_interpolation.py
#      - run:
#          name: test_interpolation_gpu
#          command: |
#            . env_fidelity/bin/activate
#            export CUDA_VISIBLE_DEVICES=0
#            python3 ./test_interpolation.py
      - run:
          name: test_convolution_cpu
          command: |
            . env_fidelity/bin/activate
            export CUDA_VISIBLE_DEVICES=""
            python3 ./test_convolution.py
#      - run:
#          name: test_convolution_gpu
#          command: |
#            . env_fidelity/bin/activate
#            export CUDA_VISIBLE_DEVICES=0
#            python3 ./test_convolution.py
      - run:
          name: test_inception_cpu
          command: |
            . env_fidelity/bin/activate
            export CUDA_VISIBLE_DEVICES=""
            python3 ./test_inception.py
#      - run:
#          name: test_inception_gpu
#          command: |
#            . env_fidelity/bin/activate
#            export CUDA_VISIBLE_DEVICES=0
#            python3 ./test_inception.py

workflows:
  main:
    jobs:
      - venv-and-test
