version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./test_interpolation_cpu.py
          name: interpolation_cpu

workflows:
  main:
    jobs:
      - build-and-test
