version: 2.1

#orbs:
#  python: circleci/python@0.2.1

jobs:
  build-and-test:
#    machine:
#      resource_class: gpu.nvidia.small
#      image: ubuntu-1604-cuda-10.1:201909-23
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv env_fidelity
            . env_fidelity/bin/activate
            pip3 install --upgrade pip
            pip3 install -r requirements_test.txt
#      - save_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
#          paths:
#            - "env_fidelity"
      - run:
          name: test_interpolation_cpu
          command: |
            . env_fidelity/bin/activate
            export CUDA_VISIBLE_DEVICES=""
            python3 ./test_interpolation.py
#      - run:
#          name: test_interpolation_gpu
#          command: |
#            . env_fidelity/bin/activate
#            export CUDA_VISIBLE_DEVICES=0
#            python3 ./test_interpolation.py

workflows:
  main:
    jobs:
      - build-and-test
