version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    machine:
      resource_class: gpu.nvidia.small
      image: ubuntu-1604-cuda-10.1:201909-23
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv env_fidelity
            . env_fidelity/bin/activate
            pip install -r requirements_test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
          paths:
            - "env_fidelity"
      - run:
          command: python ./test_interpolation_cpu.py
          name: interpolation_cpu
#    executor: python/default
#    steps:
#      - checkout
#      - python/load-cache
#      - python/install-deps
#      - python/save-cache
#      - run:
#          command: python ./test_interpolation_cpu.py
#          name: interpolation_cpu

workflows:
  main:
    jobs:
      - build-and-test
